### ISSUE TITLE
Centralized Top-level Navigation

### ISSUE THREAD

**Issue by jacobprall** [sqlitecloud/docs#16]
Currently, users have to go between different docs pages to reach information. We want to centralize all navigation onto one page, so the user can browse all info from the left-hand nav. 

Note: This change will not take place until all new documentation is complete.

**Comment by TizianoT** [comment]
Compared to the current sidebar we should have 3 hierarchical levels. Whil actual sidebar has at maximum 2 levels.
Am I right?

**Comment by jacobprall** [comment]
I think of it like this
header - no page (level 0)
Nav item - page or no page with dropdown (level 1)
Inner nav item - page or page and dropdown (level 2)
Inner inner nav item - page (level 3, max)

**Comment by TizianoT** [comment]
Todoo:
- [ ] Fix highlighting of the selected page in the left navigation bar
- [ ] Check scroll position when navigating to a new page
- [ ] Check opening state when navigating to a new page
