### ISSUE TITLE
php / update documentation

### ISSUE THREAD

**Issue by danielebriggi** [sqlitecloud/docs#2]
Namespace and classes name are changed.

**Comment by jacobprall** [comment]
@unatarajan Could you take a look at this?

**Comment by unatarajan** [comment]
- Created a [PR](https://github.com/sqlitecloud/docs/pull/80) adding significant clarifying details to the PHP Introduction.
NOTE to self: Methods were originally documented [here](https://github.com/sqlitecloud/docs/blob/26b78986edfdbae3fdd5847b899e3ce09ddb576c/sdk/php/connect.mdx).

- Created a [PR](https://github.com/sqlitecloud/sqlitecloud-php/pull/8) for the SQLite PHP SDK to fix a typo in the code for the Admin Dashboard.

- The [PHP/ Laravel Quickstart](https://docs.sqlitecloud.io/docs/quick-start-php-laravel) still works.

**Comment by danielebriggi** [comment]
@jacobprall  the PHP/Laravel guide is a bit unfair since is used to use the Eloquent orm in Laravel :D hope to adapt the sdk soon!

**Comment by unatarajan** [comment]
@danielebriggi I didn't need to use an Eloquent Model in the the Quickstart. I only set up a Controller and the SDK functions were sufficient to demo SQLite Cloud.

**Comment by danielebriggi** [comment]
> @danielebriggi I didn't need to use an Eloquent Model in the the Quickstart. I only set up a Controller and the SDK functions were sufficient to demo SQLite Cloud.

for sure, the quickstart is correct per sè. I mean that a real support of SQLite Cloud in Laravel is obtained by changing the `config/database.php` configuration to `sqlitecloud`, instead of the direct usage of the library.
