### ISSUE TITLE
Improve Vector extension doc

### ISSUE THREAD

**Issue by marcobambini** [sqlitecloud/docs#83]
From @gionatamettifogo:

> in the vector documentation... does it make sense for us to explain that the search is "brute force" also referred to as linear or full scan by more marketing minded individuals and completely normal in the database world... are we trying to undermine our own product? would we want to explain what a vector is, how it's useful, for newbies? do we want to say it doesn't quite work with free plans when it probably works fine with thousands of vectors which are most rag apps?

my reply:

> I agree that we can surely improve the message. Our goal should be to encourage experimenting and building with our tech, even in the free plan. The free plan already has several limitations, so users will naturally upgrade their plan when they need more resources. Due to how it has been developed, the sqlite-vec extension should work fine even in the free plain. @Jacob Prall I already opened a GitHub issue about this.

**Comment by jacobprall** [comment]
I think its important to set expectations around performance! If they are serious about vector workloads, they will be familiar with different indexing techniques (which we don't yet support). I also want anyone who is serious about this feature to reach out! I tweaked the copy to better align with these comments 👍
